#### 🧱 Basics

In [1]:
import numpy as np

#### Create 1D array

In [2]:
arr1 = np.array([10,11,12])
print(arr1)

[10 11 12]


#### Create 2D array

In [3]:
arr2 = np.array([[10,11,12],[4,5,6]])
print(arr2)

[[10 11 12]
 [ 4  5  6]]


#### 📐 Shape & Dimensions

#### Print shape of arrays

In [4]:
print(arr1.shape)

(3,)


In [5]:
print(arr1.shape)

(3,)


#### Print number of dimensions (ndim)

In [6]:
print(arr1.ndim)

1


In [7]:
print(arr2.ndim)

2


#### 🔄 Reshaping

#### Convert 1D array → 2D

In [8]:
reshaped = arr2.reshape(3,2)
print(reshaped)

[[10 11]
 [12  4]
 [ 5  6]]


#### 🔍 Indexing & Slicing

#### Get first row of 2D array

In [9]:
print(arr2[0])

[10 11 12]


#### Get second column

In [10]:
print(arr2[:,1])

[11  5]


#### Access a single element

In [11]:
print(arr2[1,1])

5


In [12]:
print(arr1[2])

12


#### ➕ Basic Operations

#### Find sum of array

In [13]:
print(arr2.sum())       # sum of all elements

48


In [14]:
print(arr2.sum(1))       # sum of raw elements

[33 15]


In [15]:
print(arr2.sum(0))       # sum of column elements

[14 16 18]


#### Find mean

In [16]:
print(arr2.mean())

8.0


In [17]:
print(arr2.mean(0))

[7. 8. 9.]


In [18]:
print(arr2.mean(1))

[11.  5.]


#### Find max

In [19]:
print(arr2.max())

12


In [20]:
print(arr2.max(0))

[10 11 12]


In [21]:
print(arr2.max(1))

[12  6]


#### ⚡ Element-wise Operations

#### Multiply array by 2

In [22]:
arr2

array([[10, 11, 12],
       [ 4,  5,  6]])

In [23]:
print(arr2*2)

[[20 22 24]
 [ 8 10 12]]


In [24]:
print(arr2[0]*2)

[20 22 24]


In [25]:
print(arr2[1,1]*4)

20


#### Add 5 to all elements

In [26]:
print(arr2+5)

[[15 16 17]
 [ 9 10 11]]


#### 🎯 Filtering

#### Extract values greater than a number

In [27]:
print(arr2[arr2>5])

[10 11 12  6]
